import type { BrandKit, BrandKitSummary, ListingCopy, ProductInsight } from "./index.js";

export type ImageSlotPlanItem = {
  slotType: string;
  slotIndex: number;
  label: string;
  prompt?: string;
};

export type CreativeBriefInput = {
  clientName?: string;
  projectName?: string;
  productContext: string;
  insights: ProductInsight[];
  brandKit?: BrandKit | BrandKitSummary | null;
  brandKitSummary?: string;
  imageSlots: ImageSlotPlanItem[];
  listingCopy?: ListingCopy | null;
  aplusSummary?: string;
};

function topInsights(insights: ProductInsight[], limit = 8): ProductInsight[] {
  const drivers = insights.filter((i) => i.conversionDriver);
  const rest = insights.filter((i) => !i.conversionDriver);
  return [...drivers, ...rest].slice(0, limit);
}

function brandSection(
  brandKit?: BrandKit | BrandKitSummary | null,
  brandKitSummary?: string,
): string[] {
  const lines: string[] = ["## Brand kit", ""];
  if (brandKitSummary?.trim()) {
    lines.push(brandKitSummary.trim(), "");
    return lines;
  }
  if (!brandKit) {
    lines.push("_No brand kit selected._", "");
    return lines;
  }
  lines.push(`- **Name:** ${brandKit.name}`);
  if ("secondaryColor" in brandKit) {
    lines.push(
      `- **Colors:** ${brandKit.primaryColor}${brandKit.secondaryColor ? ` / ${brandKit.secondaryColor}` : ""}`,
    );
    if (brandKit.fontFamily) lines.push(`- **Font:** ${brandKit.fontFamily}`);
    if (brandKit.toneOfVoice) lines.push(`- **Tone:** ${brandKit.toneOfVoice}`);
  } else if (brandKit.primaryColor) {
    lines.push(`- **Primary color:** ${brandKit.primaryColor}`);
  }
  lines.push("");
  return lines;
}

export function formatCreativeBrief(input: CreativeBriefInput): string {
  const lines: string[] = [
    "# Creative brief",
    "",
    `_Generated by Amzi Loci · ${new Date().toLocaleDateString()}_`,
    "",
  ];

  if (input.clientName || input.projectName) {
    lines.push("## Project", "");
    if (input.clientName) lines.push(`- **Client:** ${input.clientName}`);
    if (input.projectName) lines.push(`- **Project:** ${input.projectName}`);
    lines.push("");
  }

  lines.push("## Product", "", input.productContext.trim() || "_Not specified_", "", "## Top insights", "");

  const insights = topInsights(input.insights);
  if (insights.length === 0) {
    lines.push("_No insights extracted yet._", "");
  } else {
    for (const insight of insights) {
      const driver = insight.conversionDriver ? " *(conversion driver)*" : "";
      lines.push(
        `- **${insight.feature}** (${insight.sentiment})${driver}`,
        `  > ${insight.sourceQuote || "—"}`,
        "",
      );
    }
  }

  lines.push(...brandSection(input.brandKit, input.brandKitSummary));

  lines.push("## Image slot plan", "");
  if (input.imageSlots.length === 0) {
    lines.push("_No images generated yet. Plan: 3 main + 5 gallery._", "");
  } else {
    for (const slot of input.imageSlots) {
      const kind = slot.slotType === "main" ? "Main" : "Gallery";
      lines.push(`- **${kind} ${slot.slotIndex + 1}:** ${slot.label}`);
      if (slot.prompt?.trim()) {
        lines.push(`  - Prompt: ${slot.prompt.trim()}`);
      }
    }
    lines.push("");
  }

  if (input.listingCopy) {
    lines.push("## Listing copy summary", "");
    lines.push(`- **Title:** ${input.listingCopy.title}`);
    lines.push(`- **Bullets:** ${input.listingCopy.bullets.length}`);
    lines.push(`- **Description:** ${input.listingCopy.description.length} chars`);
    lines.push("");
  }

  if (input.aplusSummary?.trim()) {
    lines.push("## A+ content", "", input.aplusSummary.trim(), "");
  }

  lines.push(
    "## Next steps",
    "",
    "1. Review insights and brand alignment",
    "2. Upload images and copy to Seller Central",
    "3. Run compliance checklist before publish",
    "",
  );

  return lines.join("\n");
}
